language: node_js
node_js:
  - "9"
dist: kodo
sudo: required
branches:
  only:
  - main
before_script:
  - npm install -g @angular/cli
script:
- ng build --prod --base-href https://ansarisaad11.github.io/search_kodo/